### ISSUE TITLE
Previously successful action is now failing

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop-docker-cli#6]
See https://github.com/rancher-sandbox/rancher-desktop-docker-cli/actions/runs/2361281287

Most likely `steps.ref.outputs.ref` always returned an empty string, but it's now an error on a newer version of `gh`.

**Comment by mook-as** [comment]
(Probably) fixed by 9229bb1848bd3467678adde1769ac8e98ac4c491.

Note that, in the run listed, there isn't even a step with the id `ref` (and has never been since that reference was introduced in e1db50660e5cec5ef38e93f0d97bdb1a1011c779), so there would not have been any sensible value there.
